import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../style/side_nav.css";
import "../style/topbar.css";
import SideManu from "../Components/AppLayouts/SideManu/page";
import Navbar from "../Components/AppLayouts/TopNavbar/page";

export const metadata = {
  title: "Api hrm",
  description: "Generated by Mamun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <div className="side_nav">
            <SideManu />
          </div>
          <div className="content shadow float-end">
            <div>
              <Navbar />
            </div>
            <div className="m-3 p-3 bg-white rounded">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
